### PR TITLE
change for select and display data

### PR DESCRIPTION
**Pull request by PiushGupta**
React App with the following feature

The react app should do three things:

Show a <select> which shows each of the rat names retrievable by http://localhost:7421/rat-names. In addition to the names of the rats, the first entry in the <select> should be No Rat.
No Rat should be selected by default.
When No Rat is selected only the <select> should be visible.
When a rat name is selected the width, height and nickname of the rat should also be shown. This information can be retrieved from http://localhost:7421/rat/${nameOfRat}. Not all rats have a nickname, for rats that have no nickname the nickname should be listed as "Uncool Rat with no Nickname".
For large screens the app should be as tall as the browser window and the select should be to the left of the rat information. For narrow screens the rat information should be below the select

### CODE REVIEW

**Comment by ohjames** [comment]
Can you please delete your form from github and send the code in a zip/archive.

**Comment by PiushGupta** [comment]
yeah sure can i get the email id to send it to.

Thanks
Piush

**Comment by PiushGupta** [comment]
[flying-rats.zip](https://github.com/sol-x/flying-rats/files/4001658/flying-rats.zip)
PFA the changes

**Comment by ohjames** [comment]
@PiushGupta Please delete your repository and email the zip rather than attaching it to this PR.

**Comment by PiushGupta** [comment]
Hi Author,

PFA the code.

Thanks
Piush

**Pull request closed without merging**
